### ISSUE TITLE
Only a note

### ISSUE THREAD

**Issue by Ennio71** [RonnyWeiss/APEX-Dynamic-Dialog-Title#1]
If you use javascript to change the title of a modal dialog **ALL** modal dialog titles, also inline regions, are changed.

Best regards
Ennio

**Comment by RonnyWeiss** [comment]
thank you will fix that

**Comment by Ennio71** [comment]
Time ago I've tried but, unfortunately, the regìon is rendered by Apex with a random id.
Working using the class affects all the dialog regions 😰
B.r. Ennio

**Comment by RonnyWeiss** [comment]
I checked the problem again and found no solution. I will close the issue now. But I will keep an eye on the problem and hope I can fix it some day.

**Comment by Jefry-nolastname** [comment]
<img width="1199" alt="Screen Shot 2021-12-11 at 11 47 34" src="https://user-images.githubusercontent.com/60998594/145664418-873004b5-051b-4941-afeb-e0323588a9cb.png">

**Comment by RonnyWeiss** [comment]
Fixed in version 23.01.12
